### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by helloalanhill**
The slash caused following comparison failed.

### CODE REVIEW

**Comment by kirb** [comment]
Really directories should be normalised with something like `$(realpath …)` for use with comparisons, so subtle things like `../` or `//` don’t break the check.

**Comment by leptos-null** [comment]
I believe this has been fixed in 19cef09f558e6cba696c54985bc0cfc558020139

**Comment by PoomSmart** [comment]
@helloalanhill You should resolve merge conflicts.

**Comment by kirb** [comment]
Going to consider this already fixed due to 19cef09, but thanks for the PR!

**Pull request closed without merging**
